spring.datasource:
  url: jdbc:mysql://localhost:3306/stackoverflow
  username: root
  password: stackoverflow
  driver: com.mysql.cj.jdbc.Driver

spring:
  jpa:
    show-sql: true
    hibernate:
      dialect: mysql
      ddl-auto: create-drop
      show_sql: true
      format_sql: true

hibernate.hbm2ddl.auto: create-drop
hibernate.show_sql: true
hibernate.format_sql: true
hibernate.use_sql_comments: true

log4j.logger.org.hibernate.SQL: debug
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE